### ISSUE TITLE
Things to fix in MAMBO patches II

### ISSUE THREAD

**Issue by GuillermoCallaghan** [GuillermoCallaghan/mambo#3]
The fixes are in progress in the [**`FIX_ERRORS`**](https://github.com/GuillermoCallaghan/mambo/tree/FIX_ERRORS) branch.
All the commits are on purpose separate as this makes it easier to see what changed.

_Most of the commits will be fixup later, once all the errors are corrected._

## [__`6f726ea`__](https://github.com/GuillermoCallaghan/mambo/commit/6f726eab63dd5926a135947610bfacef2e8c17f2): _[AArch64] Fix signal handling for continuous traces_

* Signal handling was designed such that the metadata contained all the information required to restore the code overwritten by the inserted `HVC` traps.

* Not opposed to just copying the code somewhere as you've done, but
  1. it should be handled the same way everywhere and
  2. there's an issue with `get_fragment_id()` **/** `addr_to_fragment_id()` which breaks this.
    * `addr_to_fragment_id()` does a binary search based on `thread_data->code_cache_meta[`*`id`*`].tpc` to identify the fragment `id`. Now consider the following case: a signal is received in an exit stub.
The fragment _`id`_ will correspond to the last trace fragment in that trace. The instructions saved by `unlink_direct_branch()` in `exit_branch_addr[]` are for the matching `bb_meta->exit_branch_addr` and not to the exit stub. Then when the inserted trap executes, the `bb_meta->exit_branch_addr` of the last trace fragment is overwritten from `exit_branch_addr`, but the trap itself is left there.

* [x] The easiest approach to avoid all these issues would be to create metadata entries for each exit stub. Then we could also get rid of the pattern matching for `HVC TRACE_EXIT_STUB`, which seems a bit fragile.
  > Commit: [__`47a2907`__](https://github.com/GuillermoCallaghan/mambo/commit/47a29072a6e8fcd14a1c45d670e83d2cdf3386e9): _[AArch64] Create metadata for each trace exit stub_
  > Commit: [__`8b062ca`__](https://github.com/GuillermoCallaghan/mambo/commit/8b062ca783fd262017cb36b175c9713859496d27): _[AArch64] Set the exit branch of exits at the same location_

* [ ] Implement the signal handling mechanism.
  > Commit: [__`45cce2a`__](https://github.com/GuillermoCallaghan/mambo/commit/45cce2a7ec5bf25734386f6d592d540f6c3bc38a): _[AArch64] Update the branch_cache_status to reflect new traces_
  > Commit: [__`67c9c73`__](https://github.com/GuillermoCallaghan/mambo/commit/67c9c73213d3a47a9f5a62fbfdccc14080933316): _Generalise the is_offset_within_range() function_

# Work In Progress
This commit implements handling signals when they happen in traces, dealing with the different layout of the traces and exits.
The exits part seems not to be working, as after an exit is restored the whole thing crashes.
For the time being an message is printed when an exit is encountered. [Here](https://github.com/GuillermoCallaghan/mambo/blob/FIX_ERRORS/signals.c#L473)
  > Commit: [__`dfef2de`__](https://github.com/GuillermoCallaghan/mambo/commit/dfef2deaa72b4775ac6793ae97dc0f33ffb10488): _WIP_

**Comment by lgeek** [comment]
Hi, I've figured out what's going wrong here.

So when a trap from a trace exit stub is executed, we go to `signal_dispatcher()` where we eventually execute `restore_exit()` - which I think restores the exit correctly - but then we hit the `sigret_dispatcher_call()` path. This is essentially setting up the signal frame so that when we sigreturn, we basically make the kernel call into the `dispatcher()` with the SPC of the target copied from `bb_meta->branch_taken_addr'.

The dispatcher is expected to see the pending signal and deliver it to the application, then when the application sigreturns to continue execution by doing a `lookup_or_scan()` on the target SPC. And here are 2 issues: 1) for the `trace_exit` type of fragment, the `branch_taken_addr` is a TPC rather than a SPC, so that will make the dispatcher re-translate some code cache code and 2) we can't necessarily provide the matching SPC for an arbitrary TPC as used for `trace_exits` (because we could be skipping over instructions in a fragment header inserted by MAMBO or by the instrumentation and because some source instructions are expanded in multiple translated instructions).

One idea I had was that we could instead pass an SPC and separately an offset in the translated code - basically jump to the translation of this SPC + x instructions in the translation. However, the problem is that we don't require the instrumentation to be deterministic - if the code cache is flushed while running the application's signal handler and then we retranslate the return fragment, then the first X instructions which we've already executed could be different. Also we'd need to store this offset somewhere (maybe in the least significant 2 bits of the SPC as a hack? spilling them to the stack would complicate things).

Maybe what we could do instead is this:
a) if a signal is delivered in a fragment which branches to a trace exit, then we can unlink the fragment as normal
b) if a signal is delivered in a trace exit itself, then we unlink the target fragment instead and leave the trace exit alone

I've not fully thought through this approach, I'm not 100% sure there's no other issue hidden somewhere.

**Comment by lgeek** [comment]
Hi, so the idea I was mentioning above seems to work. Meanwhile, I've also warmed up to the idea of storing a copy of the instructions when unlinking a direct branch for signal delivery, as you've done initially. I think that helps somewhat with the code duplication that was happening in your WIP commit to deal with restoring exits and it should also make it faster to get RISC-V supported. So I wrote a patch to do it for all direct branches: https://github.com/lgeek/dbm/commit/167f93241838e2efe947f074d2c14278b034b818

This is essentially replacing your WIP patch in terms of functionality. You can also take this bit and apply it to `WIP` to get it to work correctly:

```
#ifdef __aarch64__
  // we don't try to unlink trace exits, we unlink the fragment they jump to
  if (bb_meta->exit_branch_type == trace_exit) {
    fragment_id = addr_to_fragment_id(current_thread, bb_meta->branch_taken_addr);
    bb_meta = &current_thread->code_cache_meta[fragment_id];
    pc = bb_meta->tpc;
  }
#endif
```

Please let me know what you think and give it a try (I've only tested it on my Arch Linux ARM laptop).
